name: demo_dart
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: geula <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
